# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Data Update

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'
  workflow_dispatch:

jobs:
  data-update:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        ref: production
    - name: Init Node 14
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install Dependencies
      run: npm ci
    - name: Fetch New Data
      run: npm run fetch-data
    - name: Commit Changes to production
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: production
        file_pattern: data.json codebook.json
        commit_message: Automated Data Update from OWID
